global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']

  - job_name: 'note-service'
    static_configs:
      - targets: ['note-service:8002']

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:8003']

  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8004'] 